### ISSUE TITLE
[Feature] Symfony - Monolog

### ISSUE THREAD

**Issue by gander** [buggregator/docs#1]
# Symfony - Monolog

## `.env.local`

```dotenv
MONOLOG_SOCKET_HOST=127.0.0.1:9913
```

## `config/packages/dev/monolog.yaml`

```yaml
monolog:
    handlers:
        socket:
            level: debug
            type: socket
            formatter: monolog.formatter.json
            connection_string: '%env(MONOLOG_SOCKET_HOST)%'
```

---

### Note:

Setting `formatter: monolog.formatter.json` is critical. Without it, you get an error similar to: https://github.com/buggregator/server/issues/87
